### PR TITLE
Support mixed instance policies.

### PR DESCRIPTION
**Pull request by deverton**
When a mixed instance policy is enabled for an autoscaling group, the
launch template value is under the mixed instances policy part of the
returned object.

### CODE REVIEW

**Comment by TwinProduction** [comment]
Nice catch!

**Comment by colinliddlemyob** [comment]
Ahah, I just encountered this issue as well, did a build off the branch and it works for me

**Comment by deitch** [comment]
Really nice catch, and a nice little `gofmt` update for icing on the cake.

**Comment by deitch** [comment]
Can you please rebase and then we can merge in right away?

Hoping everyone is healthy.

**Comment by deverton** [comment]
I've merged in master so it should be up to date. Do you want an actual rebase and force push?

**Comment by deitch** [comment]
All good, thanks.

**Comment by deverton** [comment]
Excellent! Thanks for merging.

**Comment by deitch** [comment]
Thanks for the PR! :-)

Have a good and healthy weekend.

**Pull request merged**
