### PR TITLE
Add builder stage to dockerfile to produce binary for scratch image

### PR DESCRIPTION
**Pull request by zaquestion**
Had some trouble with the dockerhub image, I image there may be some complexity with the build environment for the container. Created this multistage docker file to push the builds into the docker file which should hopefully streamline deploying new versions at least.

For reference, heres the error I ran into
```
$ docker run deitch/aws-asg-roller:12725ef2edf484bcd54145a9c66cd6690bcd4cae
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

Haven't started using the tool yet, but thanks for writing this! Really great explanation of the problem domain in your README and very much the solution to the problem I was looking for.

### CODE REVIEW

**Comment by deitch** [comment]
> Really great explanation of the problem domain in your README and very much the solution to the problem I was looking for

Thank you. I am a quite focused on documentation of problems and solutions. Been working with a company for the past six weeks, 90% of what I have done is document how things work and how they should.

This definitely needs real work. It is intended to solve a real problem for a real company, but they have had me focus on other priorities. As people contribute, I will be able to make it better.

**Comment by deitch** [comment]
As for this PR, I am very torn. On the one hand, I do look multistage builders. On the other hand, go cross-compiling is fantastically good and quick, and gives you binaries you can work with locally outside of the packaged image.

I am going to look at this issue and see if it can be fixed first, then we can look at build process as a separate question.

**Comment by deitch** [comment]
Yes, looks like it got built in a bad fashion. I am going to fix this manually immediately so that it works, then look at the build process.

**Comment by deitch** [comment]
Pushed.

**Comment by deitch** [comment]
Also migrated to go modules. :-)

**Comment by zaquestion** [comment]
Updated this branch with changes from master. I'd still recommend adopting something like this so that your docker builds are completely independent of your build environment. Particularly since it doesn't impact the ability to cross-compile locally or other build/packaging processes.

> On the other hand, go cross-compiling is fantastically good and quick, and gives you binaries you can work with locally outside of the packaged image.

**Comment by deitch** [comment]
> Updated this branch with changes from master

Needs updating again, probably because of your last PR :-)

> I'd still recommend adopting something like this so that your docker builds are completely independent of your build environment.

Yes, indeed. I know you are right, and I use that same structure in a _lot_ of places. I remember vividly the headaches I used to jump through to get the equivalent of multi-stage docker builds before they actually had them. Dealing with precisely this in another place.

**Comment by deitch** [comment]
> Particularly since building in docker doesn't impact the ability to cross-compile locally or other build/packaging processes

I am not wholly convinced this is right. More accurately, I am not convinced that multistage doesn't impact it.

The current build process actually _is_ docker-friendly. 

```sh
$ make build.                                       # builds the image locally using local go install
$ make build DOCKERBUILD=true    # builds the image in docker
```

Both of the above run `go mod download` and `go build` in a docker build env, so local build env will not matter. However, both put artifacts into `$PWD/bin/`, which allows for looking at the binary, etc. with ease. It also gives me the option to run the build locally or in docker without having duplicate anything. The `Dockerfile` then is used solely for building a distribution image.

Using a multi-stage `Dockerfile`, however, _everything_ is inside, which:

* makes accessing individual stages harder (just had to deal with that)
* leaves the build artifact inside the container

That having been said, I guess you always could do it the other way around: have the `Dockerfile` be multistage build, and then have the `build` target be:

```makefile
build:
        docker build -t someimage:sometag .
        docker run --rm someimage:sometag cat /aws-asg-roller > bin/aws-asg-roller-$(OS)-$(ARCH)
```

or something similar. 

For now, going to change the default to build in docker by default, then override via `make build BUILD=local`. That at least eliminates any issue of build environment (other than docker of course). 

We can keep the multistage discussion going.

**Comment by deitch** [comment]
I took a stab at getting the entire `Makefile` to work correctly with multistage builds. Not wholly convinced by it, but worth the discussion. See #14

**Comment by zaquestion** [comment]
> leaves the build artifact inside the container

Might be misunderstanding here, but this is actually the key benefit with multistage builds, once you employ a new `FROM` directive your starting the next stage and discarding the rest. You can copy things from previous stages, but you remain with a minimal image at the end.

**Comment by deitch** [comment]
> Might be misunderstanding here, but this is actually the key benefit with multistage builds, once you employ a new FROM directive your starting the next stage and discarding the rest. You can copy things from previous stages, but you remain with a minimal image at the end

Correct. But if you want the build artifact outside the container for any reason, you have to do some extra work to get it.

Multistage Dockerfiles are optimized towards the results being in the image. If your final target artifact is _just_ an image, then it is great. If it is not (only) an image, e.g. you want the binary locally, you have to do extra work to get there.

**Comment by zaquestion** [comment]
> But if you want the build artifact outside the container for any reason, you have to do some extra work to get it.

Made the same point on #14 but just for the record in this thread...

Building the binary as part of the `docker build` and building the binary locally isn't mutually exclusive. Both useful for the respective cases.

**Comment by deitch** [comment]
> Building the binary as part of the docker build and building the binary locally isn't mutually exclusive. Both useful for the respective cases

Definitely agree. The `Makefile` in #14 does just that, you can run `make build` or `make build BUILD=local` to get different build locations.

**Comment by zaquestion** [comment]
The feature here isn't an additional build location. Its a self contained `Dockerfile`, the only step required being a `docker build .` and you have a working image inline with the expectations of a typical docker user with no setup beforehand required.

**Comment by deitch** [comment]
> The feature here isn't an additional build location. Its a self contained Dockerfile, the only step required being a docker build . and you have a working image inline with the expectations of a typical docker user with no setup beforehand required

So there is the difference, I think. I tend to focus on:

* typical docker user: `docker run <imgname>`
* typical engineer: `git clone ... && <something>`

Once we are up to `git clone` and building locally, `make build` is no different. I don't tend to see a "middle level" of "I am ok with `git` and some other things but not `make`.

**Comment by zaquestion** [comment]
It's not an anti make thing, I'm happy to use `make build` to build a binary. To build a docker image ideally I want a `docker build` to create a functional image without any additional steps.
```
docker build .
```
vs 
```
make build
docker build .
```

Benefit of this change would be that `make build` etc still works as expected and that workflow remains unimpacted while making the docker build process self contained and repeatable.

Looking back on what prompted this PR would seem like a justifiable case on its on.

> Yes, looks like it got built in a bad fashion. I am going to fix this manually immediately so that it works, then look at the build process.

Taking the approach here would ensure bad builds don't happen because they simply won't be based on how the user/makefile/etc builds the binary, its defined in the Dockerfile. Biggest concern with #14 is that you don't really get away from this issue since you can specify build-args with different arch/os increasing the risk of pushing an improperly built image.

**Comment by deitch** [comment]
> vs
>
> make build
> docker build .

Actually, `make image` will do exactly what you are asking.

If you are suggesting, let's have someone running `docker build .` automatically do the build+image, whereas `make image` will do the same thing but `make build` will create the binary (with or without also doing the image), it isn't a bad idea, as long as it doesn't come at the cost of also being able to build for different OSes and archs. 

> ensure bad builds don't happen because they simply won't be based on how the user/makefile/etc builds the binary, its defined in the Dockerfile

I get that, I really do, but is it any better to define it in the `Dockerfile` vs the `Makefile`? Is `docker build .` _really_ better than `make image`?

That having been said, as I wrote above, I really do get it. Having all of it defined in the `Dockerfile` does make it easier, but it also leads to potential duplication. These things start out with "just in these two places" but inevitably something breaks as they drift apart.

Speaking of which, did you see the experimental work announced at DockerCon yesterday, where you can do `docker build --target=linux/arm64,windows/amd64 --push .` to build different archs and get a multi-arch manifest (or any part thereof)? Should ease a lot of things up.

> you can specify build-args with different arch/os increasing the risk of pushing an improperly built image

Let's turn it around. Instead of my explaining why we need it to build for multiple arch/os, I will "open my mind" (to quote Morpheus). How would you do it so that you can build for multiple arch/os?

**Comment by deitch** [comment]
FWIW, I am enjoying this conversation. It cuts very much to the heart of a philosophy of build tool chains. These _matter_.

**Comment by deitch** [comment]
Also, interestingly, you do not _have_ to set the build args. If you leave them blank - just `docker build .` - you end up with whatever the default platform is.

**Pull request closed without merging**
