### PR TITLE
Fix neglected logs

### PR DESCRIPTION
**Pull request by TwinProduction**
It's me again 😎 

It appears two logs slipped by.

### CODE REVIEW

**Comment by deitch** [comment]
Haha! No worries. Funny that CI isn't running. I will see if I can kick it off.

**Comment by deitch** [comment]
I have no idea why. Can you make a noop change and force-push, see if that kicks it off?

**Comment by TwinProduction** [comment]
@deitch Done

**Comment by deitch** [comment]
Looks like github actions has an outage. Let's wait and I will re trigger.

**Comment by deitch** [comment]
Still misbehaving. I had some issues with the action checkout@v1, so see if changing to @v2 works?

**Comment by TwinProduction** [comment]
Here we go

**Comment by deitch** [comment]
it is much happier now. Thanks.

**Pull request merged**
