### PR TITLE
fix: skip updating asgs with no outdated instances

### PR DESCRIPTION
**Pull request by zaquestion**

### CODE REVIEW

**Comment by deitch** [comment]
This is a good fix, but tests fail. We need either to fix the logic, or fix the tests if in error.

**Comment by zaquestion** [comment]
Updated the tests to provide a more accurate look at the state of variables when the roller is running. Its hard to reason about what all those maps will be from the perspective of the adjust func. Longer term I'd like to refactor `adjust` to require less state to manage the new/original desired settings. In the meantime hopefully these tests will suffice.

**Comment by deitch** [comment]
Hats off, this is a nice job. 

Please just rebase and we can merge in.

Yeah, I know, travis is broken....

**Comment by zaquestion** [comment]
In case the rebase doesn't trigger a notification heres a comment letting you know I pushed it :D

**Comment by deitch** [comment]
Ha! No, GitHub doesn't trigger that. Although when I switch to GH actions (if I get past the issues), it should.

**Pull request merged**
